# Generated by Django 5.0.7 on 2025-01-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('conference', models.CharField(choices=[('East', 'Eastern Conference'), ('West', 'Western Conference')], max_length=10)),
            ],
        ),
    ]
