# Generated by Django 5.0.7 on 2025-02-17 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='position',
        ),
        migrations.RemoveField(
            model_name='player',
            name='team_east',
        ),
    ]
