# Generated by Django 5.0.7 on 2025-02-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_player_position_player_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(default='', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
