# Generated by Django 5.0.7 on 2025-02-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_player_rank_alter_player_position_alter_player_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
