# Generated by Django 5.0.7 on 2025-02-17 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_player_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='rank',
        ),
    ]
