# Generated by Django 5.0.7 on 2025-02-17 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_player_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='url',
        ),
    ]
