# Generated by Django 5.1.6 on 2025-02-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_player_age_player_ast_player_awards_player_blk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='awards',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
