# Generated by Django 5.1.6 on 2025-02-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_alter_player_awards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='awards',
            field=models.CharField(default='-', max_length=100, null=True),
        ),
    ]
