# Generated by Django 5.1.6 on 2025-03-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_alter_player_ast_alter_player_blk_alter_player_bpm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='image_url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
