# Generated by Django 5.1.6 on 2025-03-27 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_player_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('source', models.URLField()),
                ('text', models.TextField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='pages.player')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
