# Generated by Django 5.1.6 on 2025-05-25 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_playernews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playernews',
            name='source',
            field=models.CharField(default='', max_length=300),
        ),
    ]
