# Generated by Django 5.1.6 on 2025-05-26 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_alter_playernews_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playernews',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.player'),
        ),
        migrations.AlterField(
            model_name='playernews',
            name='source',
            field=models.CharField(max_length=255),
        ),
    ]
