# Generated by Django 5.1.6 on 2025-05-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_alter_playernews_player_alter_playernews_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playernews',
            name='source',
            field=models.CharField(max_length=500),
        ),
    ]
