# Generated by Django 5.1.6 on 2025-06-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_team_teamplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='neg',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='neu',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='pos',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
