services:
  web:
    build: ./app
    ports:
      - 8000:8000
    volumes:
      - ./app/:/app
    command: >
      sh -c "python manage.py fetch_players
             python manage.py fetch_teams
             gunicorn mywebsite.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      - db
    environment:
      DB_HOST: ${POSTGRES_HOST}
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web

  
volumes:
  postgres_data:
