# Generated by Django 5.0.7 on 2025-02-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_player_position_remove_player_team_east'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.CharField(default='', max_length=100),
        ),
    ]
