# Generated by Django 5.0.7 on 2025-02-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_player_position_alter_player_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='rank',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.CharField(default='', max_length=100),
        ),
    ]
