# Generated by Django 5.0.7 on 2025-02-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_alter_player_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
