services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      
  web:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ../../staticfiles:/staticfiles
    command: >
      sh -c "python manage.py fetch_players &&
            python manage.py fetch_teams &&
            python manage.py fetch_news &&
            python manage.py collectstatic --noinput &&
            python manage.py migrate &&
            gunicorn mywebsite.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      - db
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}


  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ../../staticfiles:/staticfiles
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web


volumes:
  postgres_data: